### ISSUE TITLE
missing stdlog terminates formatting

### ISSUE THREAD

**Issue by rousskov** [Mark-Simulacrum/attractifier#12]
```
Error thrown, getting position. Error: { Error: EINVAL: invalid argument, write
    at Proxy.writeSync (fs.js:568:3)
    at log (/usr/lib/node_modules/attractifier/src/utils.js:114:26)
    at CodeGenerator.lineLog (/usr/lib/node_modules/attractifier/src/CodeGenerator.js:62:13)
    at CodeGenerator.enterPrint (/usr/lib/node_modules/attractifier/src/CodeGenerator.js:643:14)
    at CodeGenerator.print (/usr/lib/node_modules/attractifier/src/CodeGenerator.js:603:31)
    at CodeGenerator._generate (/usr/lib/node_modules/attractifier/src/CodeGenerator.js:173:14)
    at CodeGenerator.generate (/usr/lib/node_modules/attractifier/src/CodeGenerator.js:222:25)
    at formatText (/usr/lib/node_modules/attractifier/src/api/node.js:33:22)
    at formatFile (/usr/lib/node_modules/attractifier/src/api/node.js:42:16)
    at Object.<anonymous> (/usr/lib/node_modules/attractifier/src/main.js:17:26) errno: -22, syscall: 'write', code: 'EINVAL' }
/usr/lib/node_modules/attractifier/src/utils.js:1
Error: EINVAL: invalid argument, write
...
Something went wrong. You may want to undo with git reset --hard.
```

AFAIK, the error code is different on other OSes.

A workaround is to add `3>&1` or a similar shell redirection that creates a "stdlog" descriptor.

**Comment by Mark-Simulacrum** [comment]
Fixed in 242b84dd2ed4c18684e4297a368c4ad75fd29daa.
